diplom_django/diplom_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('works.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diplom_django/works/urls.py
from django.urls import path

from works.views import *

app_name = "works"
urlpatterns = [
    path('', index, name='home'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
    path('works/list/', WorkListView.as_view(), name='works_page'),
    path('works/list/<int:work_type_id>/<int:year_id>/', WorkListView.as_view(), name='works_pages'),
    path('works/<int:pk>/update', WorkUpdateView.as_view(), name='work_page'),
    path('works/<int:pk>/change', StaffWorkUpdateView.as_view(), name='staff_work_page'),
    path('works/<int:pk>/delete', WorkDeleteView.as_view(), name='delete_work_page'),
    path('works/new_work_page/<int:work_type_id>', new_work_page, name='new_work_page'),
    path('works/works_page_navform/', works_navform, name='works_page_navform'),
]

diplom_django/works/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def validate_grade(value):
    if isinstance(value, int) and value not in (3, 4, 5):
        raise ValidationError(
            _('%(value)s is not in (3, 4, 5)'),
            params={'value': value},
        )


class WorkType(models.Model):
    name = models.CharField(max_length=255, verbose_name='Тип работы')
    url_slug = models.IntegerField(verbose_name='URL slug', blank=True, null=True, unique=True)

    def __str__(self):
        return self.name


class AcademicYear(models.Model):
    name = models.CharField(max_length=255, verbose_name='Учебный год')
    url_slug = models.IntegerField(verbose_name='URL slug', unique=True)

    def __str__(self):
        return self.name


class Work(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название работы', blank=True)
    file = models.FileField(upload_to='works/', verbose_name='Файл', blank=True)
    upload_date = models.DateField(auto_now=True, verbose_name='Дата загрузки')
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE, verbose_name='Учебный год', blank=True,
                                      null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец работы', related_name='owner')
    work_type = models.ForeignKey(WorkType, on_delete=models.CASCADE, verbose_name='Тип работы')
    status = models.CharField(max_length=255, verbose_name='Состояние', default='Ожидается загрузка файла')
    is_accepted = models.BooleanField(default=False, verbose_name='Работа принята')
    scientific_director = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Научный руководитель',
                                            related_name='scientific_director', blank=True, null=True)
    grade = models.IntegerField(verbose_name='Оценка', validators=[validate_grade], blank=True, null=True)

    def __str__(self):
        return f'id:{self.id} {self.name}'

    def get_absolute_url(self):
        return reverse('works:work_page', kwargs={"pk": self.id})

diplom_django/works/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput, Select, FileInput, PasswordInput, CheckboxInput, Form, ModelChoiceField, \
    NumberInput

from works.models import Work, WorkType, AcademicYear


class WorksFilterForm(Form):
    work_type = ModelChoiceField(label="", queryset=WorkType.objects.all(), empty_label=None, to_field_name="url_slug",
                                 widget=Select(attrs={'class': 'form-control'}))
    academic_year = ModelChoiceField(label="", queryset=AcademicYear.objects.all(), empty_label=None,
                                     to_field_name="url_slug",
                                     widget=Select(attrs={'class': 'form-control'}))


class WorkForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Work
        fields = ['name', 'file']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название работы'}),
            # 'work_type': Select(attrs={'class': 'form-control'}),
            # 'file': FileInput(attrs={'class': 'form-control-file'}),
        }


class WorkFormCreate(WorkForm):
    # academic_year = ModelChoiceField(label="Учебный год", queryset=AcademicYear.objects.all(), empty_label=None,
    #                                  to_field_name="url_slug",
    #                                  widget=Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['academic_year'].empty_label = None
        self.fields['owner'].empty_label = '--- Выберите студента ---'

    class Meta:
        model = Work
        fields = ['name', 'academic_year', 'file', 'owner', 'grade', 'is_accepted']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название работы'}),
            'work_type': Select(attrs={'class': 'form-control'}),
            'academic_year': Select(attrs={'class': 'form-control'}),
            'owner': Select(attrs={'class': 'form-control'}),
            'grade': NumberInput(attrs={'class': 'form-control'}),
            'is_accepted': CheckboxInput(attrs={'class': 'form-check-input lg',
                                                'style': 'margin-left:20px; margin-top:8px; transform: scale(1.5); '
                                                         '-webkit-transform: scale(1.5);'}),
            # 'file': FileInput(attrs={'class': 'form-control-file'}),
        }


class RegisterUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'password1': PasswordInput(attrs={'class': 'form-control'}),
            'password2': PasswordInput(attrs={'class': 'form-control'}),
        }


class LoginUserForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    # class Meta:
    #     model = User
    #     fields = ['username', 'password1', 'password2']
    #     widgets = {
    #         'username': TextInput(attrs={'class': 'form-control'}),
    #         'password1': PasswordInput(attrs={'class': 'form-control'}),
    #         'password2': PasswordInput(attrs={'class': 'form-control'}),
    #     }

diplom_django/works/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from works.forms import WorkForm, RegisterUserForm, LoginUserForm, WorkFormCreate, WorksFilterForm
from works.models import Work, WorkType, AcademicYear


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('works:login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('works:home')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

    def get_success_url(self):
        return reverse_lazy('works:works_page')


class WorkListView(LoginRequiredMixin, ListView):
    model = Work
    template_name = 'works.html'
    context_object_name = 'works'

    def _get_queryset_if_is_staff(self, **kwargs):
        if self.request.user.is_staff:
            return super().get_queryset().filter(scientific_director=self.request.user, **kwargs)
        else:
            return super().get_queryset().filter(owner=self.request.user, **kwargs)

    def get_queryset(self):
        work_type_slug = self.kwargs.get('work_type_id')
        year_slug = self.kwargs.get('year_id')

        if work_type_slug is None and year_slug is None:
            return self._get_queryset_if_is_staff()
        else:
            return self._get_queryset_if_is_staff(work_type__url_slug=work_type_slug,
                                                  academic_year__url_slug=year_slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = WorksFilterForm(initial={'work_type': self.kwargs.get('work_type_id'),
                                                   'academic_year': self.kwargs.get('year_id')})
        if self.kwargs.get('work_type_id'):
            context['work_type'] = WorkType.objects.get(url_slug=self.kwargs.get('work_type_id'))
        else:
            context['work_type'] = WorkType.objects.all()[0]
        return context


class WorkUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = WorkForm
    model = Work
    template_name = 'work.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        if 'change' in self.request.POST:
            instance.status = 'На проверке'
        return super(WorkUpdateView, self).form_valid(form)

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class StaffWorkUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = WorkFormCreate
    model = Work
    template_name = 'work.html'

    def test_func(self):
        obj = self.get_object()
        return obj.scientific_director == self.request.user

    def get_success_url(self):
        obj = self.get_object()
        return reverse('works:staff_work_page', args=[obj.pk])

    def form_valid(self, form):
        instance = form.save(commit=False)
        if 'revision' in self.request.POST:
            instance.status = 'На доработке'
        if 'delete' in self.request.POST:
            return redirect(reverse('works:delete_work_page', kwargs={'pk': instance.pk}))
        if 'change' in self.request.POST and instance.is_accepted:
            instance.status = 'Работа принята'
        return super(StaffWorkUpdateView, self).form_valid(form)


class WorkDeleteView(DeleteView):
    model = Work
    success_url = reverse_lazy('works:works_page')
    template_name = 'work_delete.html'


def index(request):
    return render(request, 'index.html')


def logout_user(request):
    logout(request)
    return redirect('works:login')


# def works_page(request):
#     if request.user.is_authenticated:
#         if request.user.is_staff:
#             works = Work.objects.filter(scientific_director=request.user)
#         else:
#             works = Work.objects.filter(owner=request.user)
#     else:
#         return redirect('works:login')
#     form = WorksFilterForm(request.GET)
#     param = {'works': works, 'form': form}
#     return render(request, 'works.html', param)


def works_navform(request):
    work_type_id = request.POST.get('work_type')
    year_id = request.POST.get('academic_year')
    return redirect(reverse('works:works_pages', kwargs={'work_type_id': work_type_id, 'year_id': year_id}))


@login_required
def new_work_page(request, work_type_id):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    work_type = WorkType.objects.get(url_slug=work_type_id)
    if request.method == 'POST':
        form = WorkFormCreate(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.scientific_director = request.user
            instance.work_type = work_type
            instance.save()
            return redirect(reverse('works:staff_work_page', kwargs={'pk': instance.pk}))

    else:
        form = WorkFormCreate()

    param = {'form': form, 'work_type': work_type}
    return render(request, 'new_work.html', param)

diplom_django/works/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ВКР, курсовые работы, практики</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css    ">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="/">Главная</a>
    <a class="navbar-brand" href="{% url 'works:works_page' %}">Список работ</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        </ul>

        {% if request.user.is_authenticated %}
        <li class="nav-item"> {{user.username}} | <a class="btn btn-outline-dark"
                                                     href="{% url 'works:logout' %}">Выйти</a></li>
        {% else %}
        <li class="nav-item"><a class="btn btn-outline-dark" href="{% url 'works:register' %}">Регистрация</a> | <a
                class="btn btn-outline-dark" href="{% url 'works:login' %}">Войти</a>
        </li>
        {% endif %}

    </div>
</nav>


{% block content %}
{% endblock %}

</body>
</html>

diplom_django/works/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container" id="page">
    <div class="page-header">
        <h1>
            Личный кабинет
            <div style="margin-top:10px" role="toolbar" class="btn-toolbar float-right">

            </div>
            <div class="clearfix"></div>
        </h1>
    </div>
    <div class="row">
        <div class="col-sm">
            <br>
            <p>
                Добро пожаловать в личный кабинет студента.
            </p>
            <p>Чтобы загрузить свои работы, пройдите в раздел "Список работ" в меню страницы.</p>
        </div>
    </div>
</div>
{% endblock %}

diplom_django/works/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container" id="page">
    <div class="page-header" style="margin-bottom:20px">
        <h1 style="text-align: center;">
            Логин
            <div class="clearfix"></div>
        </h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <form method="post">
                {% csrf_token %}

                <div class="form-error">{{ form.non_field_errors }}</div>

                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}

                <button class="btn btn-outline-primary" type="submit">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diplom_django/works/templates/new_work.html
{% extends 'base.html' %}
{% block content %}
<div class="container" id="page">
    <div class="page-header">
        <h1>
            Новый процесс: {{ work_type.name }}
            <div style="margin-top:10px" role="toolbar" class="btn-toolbar float-right">
                <a class="btn btn-outline-secondary" href="{% url 'works:works_page' %}">
                    Вернуться к списку
                </a>
            </div>
            <div class="clearfix"></div>
        </h1>
    </div>
    <div class="row">
        <div class="col-sm">
            <form  method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-error">{{ form.non_field_errors }}</div>

                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}


                <button class="btn btn-success" type="submit">Добавить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diplom_django/works/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css    ">
</head>
<body>
<div class="container" id="page">
    <div class="page-header" style="margin-bottom:20px">
        <h1 style="text-align: center;">
            Регистрация
            <div class="clearfix"></div>
        </h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-outline-primary" type="submit">Регистрация</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

diplom_django/works/templates/work.html
{% extends 'base.html' %}
{% block content %}
<div class="container" id="page">
    <div class="page-header">
        <h1>
            Изменить работу
            <div style="margin-top:10px" role="toolbar" class="btn-toolbar float-right">
                <a class="btn btn-outline-secondary" href="{% url 'works:works_page' %}">
                    Вернуться к списку
                </a>
            </div>
            <div class="clearfix"></div>
        </h1>
    </div>
    <div class="row">
        <div class="col-sm">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-error">{{ form.non_field_errors }}</div>

                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <div style="border-color: #AAE9ED; background-color: #E7E9EB; border-radius: 5px;  box-sizing: border-box;"
                     class="container-fluid">
                    <div class="btn-toolbar justify-content-between" role="toolbar">
                        <div class="btn-group" role="group">
                            <button style="margin-left:10px;margin-top:10px;margin-bottom:10px;" class="btn btn-success"
                                    name="change" type="submit">Изменить
                            </button>
                        </div>
                        {% if user.is_staff %}
                        <div role="group">
                            {% if not object.is_accepted %}
                            <button style="margin-left:10px;margin-top:10px;margin-bottom:10px;"
                                    class="btn btn-warning text-white" name="revision" type="submit">Отправить на
                                доработку
                            </button>
                            {% endif %}
                            <button style="margin-left:10px;margin-top:10px;margin-bottom:10px;" class="btn btn-danger"
                                    name="delete" type="submit">Удалить
                            </button>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diplom_django/works/templates/work_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="container" id="page">
    <div class="row justify-content-center ">
        <div class="form" style="position: fixed; top: 30%;">
            <form method="post" >
                {% csrf_token %}
                <h3 style="margin-bottom:20px;">Удалить "{{ object.name }}"?</h3>
                <div class="btn-toolbar justify-content-center" role="toolbar">
                    <button class="btn btn-danger" type="submit">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diplom_django/works/templates/works.html
{% extends 'base.html' %}
{% block content %}
<div class="container" id="page">
    <div class="page-header" style="margin-bottom:20px">
        <h1>
            ВКР, курсовые работы, практики
            {% if user.is_staff %}
            <div style="margin-top:10px" role="toolbar" class="btn-toolbar float-right">
                <a  class="btn btn-primary btn-block float-left"
                   href="{% url 'works:new_work_page' work_type.url_slug %}"><span
                        class="glyphicon glyphicon-eye-open"></span>
                    Новый процесс: {{ work_type.name }}
                </a>
            </div>
            {% endif %}
            <div class="clearfix"></div>
        </h1>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <form action={% url 'works:works_page_navform' %} method="post">
                {% csrf_token %}
                <p> {{ form.work_type }}</p>
                <p> {{ form.academic_year }}</p>
            <button class="btn btn-primary" type="submit">Найти</button>
            </form>
        </div>
        <div class="col-sm-9">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                {% if not works.exists %}
                <div><tr>
                    <td>
                        <div style="margin-bottom:2px">Нет доступных работ у данного пользователя.</div>
                    </td>
                </tr></div>
                {% else %}
                    {% for work in works %}
                    <tr>
                        <td>
                            <a class="btn btn-outline-primary float-right"
                               href="{% if user.is_staff %}{% url 'works:staff_work_page' work.pk %}{% else %}{% url 'works:work_page' work.pk %}{% endif %}"><span
                                    class="glyphicon glyphicon-eye-open"></span>
                                Изменить
                            </a>
                            <h4>
                                <div style="margin-bottom:2px"><strong>{{ work.name }}</strong>.</div>
                            </h4>
                            <div style="margin-bottom:2px">
                                {% if user.is_staff %}
                                Студент <strong> {{ work.owner }}</strong>
                                {% else %}
                                Руководитель <strong>{{ work.scientific_director }}</strong>
                                {% endif %}
                            </div>
                            <div style="margin-bottom:2px"><strong> {{ work.work_type.name }}</strong>,
                                {{ work.academic_year.name }}
                            </div>
                            <div style="margin-bottom:2px">
                                {% if work.is_accepted %}
                                <span class="badge bg-success text-dark">{{ work.status }}</span>

                                <div>
                                    Работа загружена: {{ work.upload_date|date:"d.m.Y" }}
                                </div>
                                {% else %}
                                <span class="badge bg-info text-dark">{{ work.status }}</span>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                <tr><td></td></tr>
                {% endif %}
                </tbody>

            </table>
        </div>
    </div>
</div>
{% endblock %}